# Generated by Django 4.2.30 on 2026-08-17 21:30

from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0002_alter_snippet_content_alter_snippet_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        help_text="Unique identifier UUIDv7",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the folder", max_length=255),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Folder creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Date of last modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Folder",
                "verbose_name_plural": "Folders",
                "db_table": "devnote_folders",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="folder",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent folder, null for a folder at the project root",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="workspace.folder",
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="project",
            field=models.ForeignKey(
                help_text="Folder associated to project",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folders",
                to="workspace.project",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                help_text="Folder holding the note, null for a note at the project root",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="workspace.folder",
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["folder", "-created_at"], name="devnote_not_folder__43e91d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(
                fields=["project", "parent"], name="devnote_fol_project_60d1ce_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=("project", "parent", "name"),
                name="unique_folder_name_in_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("project", "name"),
                name="unique_folder_name_at_root",
            ),
        ),
    ]
