# Generated by Django 4.2.30 on 2026-08-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0003_folder_note_devnote_not_folder__43e91d_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="is_pinned",
            field=models.BooleanField(
                default=False, help_text="Whether the note is pinned for quick access"
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["project", "is_pinned"], name="devnote_not_project_284c68_idx"
            ),
        ),
    ]
