# Generated by Django 4.2.30 on 2026-08-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0004_note_is_pinned_note_devnote_not_project_284c68_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="is_pinned",
            field=models.BooleanField(
                default=False,
                help_text="Whether the snippet is pinned for quick access",
            ),
        ),
        migrations.AddIndex(
            model_name="snippet",
            index=models.Index(
                fields=["project", "is_pinned"], name="devnote_sni_project_1defa3_idx"
            ),
        ),
    ]
