# Generated by Django 4.2.30 on 2026-08-18 17:17

from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0005_snippet_is_pinned_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TodoList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        help_text="Unique identifier UUIDv7",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the list", max_length=255),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="List creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Date of last modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "TODO list",
                "verbose_name_plural": "TODO lists",
                "db_table": "devnote_todo_lists",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="todolist",
            name="project",
            field=models.ForeignKey(
                help_text="List associated to project",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todo_lists",
                to="workspace.project",
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="list",
            field=models.ForeignKey(
                blank=True,
                help_text="List holding the TODO, null for an unclassified TODO",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="todos",
                to="workspace.todolist",
            ),
        ),
        migrations.AddIndex(
            model_name="todo",
            index=models.Index(
                fields=["project", "list"], name="devnote_tod_project_f1a286_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="todolist",
            index=models.Index(
                fields=["project", "name"], name="devnote_tod_project_577a68_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="todolist",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_todo_list_name_in_project"
            ),
        ),
    ]
