# Generated by Django 4.2.30 on 2026-08-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0006_todolist_todo_devnote_tod_project_f1a286_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todolist",
            options={
                "ordering": ["-is_permanent", "name"],
                "verbose_name": "TODO list",
                "verbose_name_plural": "TODO lists",
            },
        ),
        migrations.AddField(
            model_name="todolist",
            name="is_permanent",
            field=models.BooleanField(
                default=False,
                help_text="Whether this list is built in and cannot be deleted",
            ),
        ),
        migrations.AddConstraint(
            model_name="todolist",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_permanent", True)),
                fields=("project",),
                name="unique_permanent_list_in_project",
            ),
        ),
    ]
