# Generated by Django 5.2.17 on 2026-08-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0009_rename_note_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="is_pinned",
            field=models.BooleanField(
                default=False, help_text="Whether the TODO is pinned for quick access"
            ),
        ),
        migrations.AddIndex(
            model_name="todo",
            index=models.Index(
                fields=["project", "is_pinned"], name="devnote_tod_project_1a192b_idx"
            ),
        ),
    ]
