# Generated by Django 5.2.17 on 2026-08-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0011_release_permanent_lists"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todolist",
            options={
                "ordering": ["name"],
                "verbose_name": "TODO list",
                "verbose_name_plural": "TODO lists",
            },
        ),
        migrations.RemoveConstraint(
            model_name="todolist",
            name="unique_permanent_list_in_project",
        ),
        migrations.RemoveField(
            model_name="todolist",
            name="is_permanent",
        ),
    ]
