# Generated by Django 5.2.17 on 2026-08-19 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0012_alter_todolist_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="folder",
            name="unique_folder_name_at_root",
        ),
        migrations.RemoveIndex(
            model_name="folder",
            name="devnote_fol_project_60d1ce_idx",
        ),
        migrations.AddField(
            model_name="folder",
            name="resource_type",
            field=models.CharField(
                choices=[("documents", "Documents"), ("snippets", "Snippets")],
                default="documents",
                help_text="Kind of resource the folder holds",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="snippet",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                help_text="Folder holding the snippet, null for a snippet at the project root",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snippets",
                to="workspace.folder",
            ),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(
                fields=["project", "resource_type", "parent"],
                name="devnote_fol_project_f39236_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="snippet",
            index=models.Index(
                fields=["folder", "-created_at"], name="devnote_sni_folder__dfb397_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("project", "resource_type", "name"),
                name="unique_folder_name_at_root",
            ),
        ),
    ]
