# Generated by Django 5.2.17 on 2026-08-21 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0013_remove_folder_unique_folder_name_at_root_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="last_opened_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date the project was last opened, null if never opened",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["user", "-last_opened_at"],
                name="devnote_pro_user_id_e31ec7_idx",
            ),
        ),
    ]
