# Generated by Django 5.2.17 on 2026-08-22 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0014_project_last_opened_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="archived_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date the project was archived, null while it is active",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="due_date",
            field=models.DateField(
                blank=True, help_text="Optional deadline of the project", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_archived",
            field=models.BooleanField(
                default=False, help_text="Whether the project is archived"
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="due_date",
            field=models.DateField(
                blank=True, help_text="Optional deadline of the TODO", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["user", "is_archived"], name="devnote_pro_user_id_be80ab_idx"
            ),
        ),
    ]
