# Generated by Django 5.2.17 on 2026-08-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0015_project_archived_at_project_due_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="due_time",
            field=models.TimeField(
                blank=True,
                help_text="Optional time of day the TODO is due, alongside its due date",
                null=True,
            ),
        ),
    ]
