# Generated by Django 5.2.17 on 2026-08-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0016_todo_due_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_favorite",
            field=models.BooleanField(
                default=False, help_text="Whether the project is marked as a favorite"
            ),
        ),
    ]
