# Generated by Django 4.2.27 on 2026-01-22 16:50

from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="name",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="Description of the project"
            ),
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        help_text="Unique identifier UUIDv7",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Name of the note", max_length=255),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, default="", help_text="Content of the note"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Note creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Date of last modification"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Note associated to project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="workspace.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
                "db_table": "devnote_notes",
                "ordering": ["-created_at"],
            },
        ),
    ]
