# Generated by Django 4.2.27 on 2026-02-03 16:12

from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snippet",
            name="content",
            field=models.TextField(help_text="Content of the snippet"),
        ),
        migrations.AlterField(
            model_name="snippet",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date creation of snippet"
            ),
        ),
        migrations.AlterField(
            model_name="snippet",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="Description of the snippet"
            ),
        ),
        migrations.AlterField(
            model_name="snippet",
            name="id",
            field=models.UUIDField(
                default=uuid6.uuid7,
                editable=False,
                help_text="Unique identifier",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="snippet",
            name="language",
            field=models.CharField(
                default="text", help_text="Language of the snippet", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="snippet",
            name="project",
            field=models.ForeignKey(
                help_text="Snippet associated to project",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snippets",
                to="workspace.project",
            ),
        ),
        migrations.AlterField(
            model_name="snippet",
            name="title",
            field=models.CharField(help_text="Title of the snippet", max_length=255),
        ),
        migrations.AlterField(
            model_name="snippet",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Date of last modification"
            ),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["project", "-created_at"], name="devnote_not_project_9c12cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="snippet",
            index=models.Index(
                fields=["project", "-created_at"], name="devnote_sni_project_0ec6e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="todo",
            index=models.Index(
                fields=["project", "-created_at"], name="devnote_tod_project_d4769b_idx"
            ),
        ),
    ]
