# Generated by Django 4.2.27 on 2026-01-25 17:12

from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):
    dependencies = [
        (
            "workspace",
            "0002_rename_name_project_title_alter_project_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(help_text="Title of the note", max_length=255),
        ),
        migrations.CreateModel(
            name="Snippet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("language", models.CharField(default="text", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snippets",
                        to="workspace.project",
                    ),
                ),
            ],
            options={
                "db_table": "devnote_snippets",
                "ordering": ["-created_at"],
            },
        ),
    ]
