# Generated by Django 4.2.27 on 2026-01-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0003_alter_note_title_snippet"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
