# Generated by Django 4.2.27 on 2026-01-26 18:05

from django.db import migrations, models
import django.db.models.deletion
import uuid6


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0004_snippet_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="TODO",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the TODO", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Optional description"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                        ],
                        default="pending",
                        help_text="Current status of the TODO",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        help_text="Priority level",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Associated project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todos",
                        to="workspace.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "TODO",
                "verbose_name_plural": "TODOs",
                "db_table": "devnote_todos",
                "ordering": ["-created_at"],
            },
        ),
    ]
